# Generated by Django 5.1 on 2024-08-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettyjobsapp', '0002_jobdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDescription',
            new_name='Job',
        ),
        migrations.CreateModel(
            name='JobImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pettyjobsapp.job')),
            ],
        ),
    ]
