# Generated by Django 5.1 on 2024-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettyjobsapp', '0003_rename_jobdescription_job_jobimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('electrical', 'Electrical')], default='mechanical', max_length=255),
        ),
    ]
