# Generated by Django 5.1 on 2024-08-23 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettyjobsapp', '0004_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='approved_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
